POST http://localhost:8000/players
Content-Type: application/json

{
    "name": "Pablo",
    "initiative": 14,
    "color":"RED"
}

###
POST http://localhost:8000/players
Content-Type: application/json

{
    "name": "Thyago",
    "initiative": 24,
    "color":"BLUE"
}

###
POST http://localhost:8000/players
Content-Type: application/json

{
    "name": "Mauro",
    "initiative": 10,
    "color": "GREEN"
}

###
GET http://localhost:8000/players
