
POST http://localhost:3000/players
Content-Type: application/json

{
    "name": "Pablo",
    "initiative": 14,
    "color":"red"
}

###
POST http://localhost:3000/players
Content-Type: application/json

{
"name": "Thyago",
"initiative": 24,
"color":"red"
}

###
POST http://localhost:3000/players
Content-Type: application/json

{
  "name": "Mauro",
  "initiative": 10,
  "color": "red"
}
